name: Code quality checks

on:
  push:
  pull_request:

jobs:
  biome:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: bun install

      - name: Run Biome with verbose output
        run: bunx biome ci . --verbose